import { randomBytes, createHash, timingSafeEqual } from "node:crypto";

/**
 * Public prefix on every raw API key (Phase 11: API + Integrations) — see
 * docs/api/api-keys.md. Distinguishes an AdstrackIO key at a glance (in
 * logs, in a support ticket, in a leaked-secret scanner) the same way
 * Stripe's `sk_live_`/GitHub's `ghp_` prefixes do.
 */
export const API_KEY_PREFIX = "atk_live_";

/**
 * How many characters of the random secret are stored in plaintext as
 * `ApiKey.keyPrefix`, purely as an O(1) lookup key before the real secret
 * is verified — never used as, or treated as, part of the actual proof of
 * possession. 10 base64url characters is 60 bits of the secret's own
 * entropy; the remaining ~198 bits (the rest of the 256-bit secret) is
 * never stored anywhere in recoverable form, so knowing the prefix alone
 * gives an attacker no meaningful head start on the full key.
 */
const LOOKUP_PREFIX_LENGTH = 10;

export interface GeneratedApiKey {
  /** The complete raw key, e.g. "atk_live_AbCdEf...". Shown to the caller
   * exactly once, at creation/rotation time — never persisted. */
  raw: string;
  /** Plaintext lookup key, stored in ApiKey.keyPrefix (unique-indexed). */
  prefix: string;
  /** SHA-256 hex digest of `raw`, stored in ApiKey.keyHash. */
  hash: string;
}

/**
 * Generates a new API key secret: 256 bits of CSPRNG randomness, base64url
 * encoded. Deliberately NOT a UUID (122 bits of entropy, and a fixed,
 * publicly-documented structure — predictable enough that it must never be
 * used as a secret) and NOT hashed with a slow password KDF — see
 * `hashApiKeySecret`'s doc comment for why.
 */
export function generateApiKey(): GeneratedApiKey {
  const secret = randomBytes(32).toString("base64url");
  const raw = `${API_KEY_PREFIX}${secret}`;
  const prefix = secret.slice(0, LOOKUP_PREFIX_LENGTH);
  return { raw, prefix, hash: hashApiKeySecret(raw) };
}

/**
 * Hashes a raw API key with SHA-256. Unlike `hashPassword` (argon2id), this
 * is intentionally a fast, non-memory-hard digest: a user password is
 * low-entropy (humans reuse short, guessable strings) and needs a slow KDF
 * to resist offline brute force, but an API key secret generated by
 * `generateApiKey` already carries 256 bits of uniform randomness — no
 * realistic offline attack against it is sped up by a fast hash, while a
 * slow one would add ~100ms+ of latency AND a trivial CPU-exhaustion
 * vector to every single public API request. This mirrors how GitHub,
 * Stripe, and most API-token systems hash tokens (see
 * docs/api/api-keys.md#hashing for the full rationale) — this codebase's
 * argon2id choice for User.passwordHash is a distinct, deliberately
 * different decision for a distinct threat model.
 */
export function hashApiKeySecret(raw: string): string {
  return createHash("sha256").update(raw).digest("hex");
}

/**
 * Constant-time comparison of a raw API key against a stored hash — never
 * a plain `===` on the digest, which would leak timing information about
 * how many leading bytes matched.
 */
export function verifyApiKeySecret(raw: string, hash: string): boolean {
  const candidate = Buffer.from(hashApiKeySecret(raw), "hex");
  let expected: Buffer;
  try {
    expected = Buffer.from(hash, "hex");
  } catch {
    return false;
  }
  if (candidate.length !== expected.length) {
    // timingSafeEqual throws on length mismatch; a malformed/foreign hash
    // never matches regardless, so short-circuit rather than throw.
    return false;
  }
  return timingSafeEqual(candidate, expected);
}

/**
 * Extracts the plaintext lookup prefix from a raw key presented at
 * authentication time (see apps/api/src/plugins/api-key-auth.ts). Returns
 * null for anything that doesn't even have the right shape — callers
 * should treat that identically to "no matching key found" (never a
 * different error), so a malformed Bearer token doesn't leak information
 * about the expected format.
 */
export function extractApiKeyLookupPrefix(raw: string): string | null {
  if (!raw.startsWith(API_KEY_PREFIX)) {
    return null;
  }
  const secret = raw.slice(API_KEY_PREFIX.length);
  if (secret.length < LOOKUP_PREFIX_LENGTH) {
    return null;
  }
  return secret.slice(0, LOOKUP_PREFIX_LENGTH);
}
