import './campaign.css';
import './campaign-bugfix.css';
import './referral.css';

import { appIcon, bindAppShell, renderAppHeader, renderAppSidebar } from './app-shell';

const icon = appIcon;
const select = (label: string, options: string[], required = false, extra = '') => `<label class="field">${label}${required ? '<b>*</b>' : ''}<select ${extra}>${options.map((o, i) => `<option ${i === 0 ? 'selected' : ''}>${o}</option>`).join('')}</select></label>`;
const input = (label: string, placeholder = '', required = false, type = 'text', extra = '') => `<label class="field">${label}${required ? '<b>*</b>' : ''}<input type="${type}" placeholder="${placeholder}" ${required ? 'required' : ''} ${extra}/></label>`;
const toggle = (label: string, checked = false, id = '') => `<label class="switch-row">${label}<span class="switch"><input type="checkbox" ${checked ? 'checked' : ''} ${id ? `id="${id}"` : ''}/><i></i></span></label>`;
const section = (title: string, body: string, collapsible = false, open = true) => `<section class="campaign-card ${collapsible ? 'accordion' : ''} ${open ? 'is-open' : ''}"><button class="section-heading ${collapsible ? 'accordion-trigger' : ''}" ${collapsible ? 'type="button" aria-expanded="' + open + '"' : 'type="button"'}><span><em></em>${title}</span>${collapsible ? `<i>${icon('chevron')}</i>` : ''}</button><div class="section-body">${body}</div></section>`;

export function mountCampaignPage(editId?: number) {
  document.title = `${editId ? 'Edit' : 'Create'} Campaign · AdstrackIO`;
  document.querySelector<HTMLDivElement>('#app')!.innerHTML = `
  <div class="campaign-app">
    ${renderAppSidebar(editId ? `/campaigns/${editId}/edit` : '/campaigns/create')}
    <main class="campaign-main">${renderAppHeader([{ label: 'Campaigns', href: '/campaigns' }, { label: editId ? 'Edit Campaign' : 'Create Campaign' }])}
      <div class="campaign-content"><div class="page-intro"><div><p class="eyebrow">CAMPAIGN MANAGEMENT</p><h1>Create Campaign</h1><p>Configure your offer, conversion flow, targeting and payouts in one place.</p></div><span class="draft-badge">Draft · Not saved</span></div>
      <form id="campaign-form" novalidate>
        ${section('Details', `<div class="objective"><span>Choose an Objective</span><div class="radio-chips">${['Conversions', 'Sale', 'App Installs', 'Leads', 'Impressions', 'Clicks'].map((x, i) => `<label><input name="objective" type="radio" ${i === 0 ? 'checked' : ''}/><i></i>${x}</label>`).join('')}</div></div><div class="form-grid"><div class="full">${select('Advertiser', ['Select an advertiser', 'Northstar Media', 'Orbit Digital', 'Bluebird Commerce'], true, 'required')}</div>${input('Campaign title', 'e.g. Summer acquisition campaign', true)}${input('KPI', 'e.g. CPA under ₹450')}<div class="full rich-field"><span>Description <small>(optional)</small></span><div class="editor"><div class="editor-tools"><button type="button"><b>B</b></button><button type="button"><i>I</i></button><button type="button">⌁</button><button type="button">☷</button><button type="button">↗</button></div><div contenteditable="true" data-placeholder="Describe this campaign for publishers..."></div></div></div><div class="full">${input('Allowed traffic channels', 'Search or select channels')}</div>${input('Preview URL', 'https://your-landing-page.com', false, 'url')}<div>${select('Conversion tracking', ['Server Postback', 'HTTPS IFrame Pixel', 'HTTPS Image Pixel'])}</div><div class="full">${input('Default campaign URL', 'https://your-landing-page.com?click_id={click_id}', true, 'url')}<p class="field-help">The destination URL for campaign traffic. Add optional parameters using the tokens below.</p><div class="tokens"><span>Most used URL tokens</span><div>${['{click_id}', '{campaign_id}', '{publisher_id}', '{source}', '{gclid}', '{fbclid}', '{app_name}', '{ip}', '{p1}', '{p2}'].map(x => `<button type="button" data-token="${x}">${x}</button>`).join('')}<a href="#">See all tokens</a></div></div></div><div class="full"><label class="field">Terms and conditions<textarea placeholder="Add campaign terms publishers must accept..."></textarea></label></div><div>${toggle('Require terms and conditions')}</div>${select('Category', ['Select a category', 'Ecommerce', 'Finance', 'Mobile Apps', 'Lead Generation'])}${select('Status', ['Active', 'Paused', 'Pending', 'Draft'])}<div class="full"><label class="field">Internal note <small>(optional)</small><textarea placeholder="Notes visible only to your team..."></textarea></label></div></div>`)}
        ${section('Revenue and Payout', `<div class="form-grid"><div class="method-group"><span>Method</span><label><input name="payout-method" type="radio" checked/> <i></i>Default</label><label><input name="payout-method" type="radio"/> <i></i>Custom</label></div><div></div>${select('Currency', ['₹ INR — Indian Rupee', '$ USD — US Dollar', '€ EUR — Euro'], true, 'required')}${input('Revenue', '0.00', true, 'number', 'min="0" step="0.01"')}<div class="full geo-choice"><span>Geo coverage</span><label class="select-pill"><input type="radio" name="geo" checked/>All geos</label><label class="select-pill"><input type="radio" name="geo"/>Specific countries</label><input class="geo-search" placeholder="Search countries or regions"/></div><div class="full payout-types"><span>Payout type</span><label><input name="payout-type" type="radio" checked/>Fixed</label><label><input name="payout-type" type="radio"/>Percentage</label><label><input name="payout-type" type="radio"/>Goal-based</label></div>${input('Payout', '0.00', true, 'number', 'min="0" step="0.01"')}<div class="payout-note"><strong>Fixed payout</strong><span>Set the amount a publisher earns per approved conversion. Percentage and goal-based payout options are also available.</span></div></div>`)}
        ${section('Advanced Settings', `<div class="form-grid advanced-grid"><div class="full visibility"><span>Visibility</span><label><input type="radio" name="visibility" checked/>Public</label><label><input type="radio" name="visibility"/>Private</label><label><input type="radio" name="visibility"/>Ask for permission</label></div>${input('Default goal name', 'Install')}${input('Default landing page name', 'Default')}<label class="field">Thumbnail <span class="file-input"><input type="file" accept="image/*"/><i>Upload image</i><small>PNG, JPG or WEBP</small></span></label>${input('App name', 'Optional app name')}${input('Conversion flow', 'e.g. install, signup, purchase')}<div class="flow-row">${select('Conversion flow language', ['English', 'Hindi', 'Spanish'])}${input('Value', 'Localized flow name')}<button type="button" class="small-add">${icon('plus')} Add</button></div>${input('Unsubscribe URL', 'https://your-domain.com/unsubscribe', false, 'url')}${input('Suppression URL', 'https://your-domain.com/suppress', false, 'url')}${input('App ID', 'Optional app identifier')}${input('External offer ID', 'Optional external ID')}${select('Redirect type', ['302 — Temporary redirect', '301 — Permanent redirect'])}${input('Unique click session duration', '168', false, 'number', 'min="1"')}<div>${toggle('Duplicate click action')}</div>${input('Conversion hold period (minutes)', '0', false, 'number', 'min="0"')}${select('Status after hold period', ['Approved', 'Pending', 'Rejected', 'Cancelled'])}<div class="full device-row"><span>Devices</span>${['All', 'Desktop', 'Mobile', 'Tablet'].map((x, i) => `<label><input type="checkbox" ${i === 0 ? 'checked' : ''}/>${x}</label>`).join('')}</div>${select('Operating system', ['All operating systems', 'Android', 'iOS', 'Windows', 'macOS'])}${input('Carrier targeting', 'Search carrier or ISP')} ${select('Deep link', ['Enabled', 'Disabled'])}${select('Allowed tracking link format', ['Numeric ID', 'Unique ID', 'Both'])}<div class="full date-switch">${toggle('Campaign start / end date', false, 'date-toggle')}<div class="date-fields">${input('Start date', '', false, 'datetime-local')}${input('End date', '', false, 'datetime-local')}</div></div><div class="full schedule-row">${toggle('Schedule status change', false, 'schedule-toggle')}<div class="schedule-fields">${select('Change status to', ['Paused', 'Active', 'Draft'])}${input('Schedule date and time', '', false, 'datetime-local')}</div></div></div>`, true)}
        ${section('Referral Settings', `<div class="referral-intro"><p>Control the referral value sent to the campaign destination.</p></div><div class="referral-options"><label class="referral-option selected"><input type="radio" name="referral-mode" value="hide" checked/><span><strong>Hide Referral</strong><small>Hide the referring URL/value from the destination.</small></span></label><label class="referral-option"><input type="radio" name="referral-mode" value="custom"/><span><strong>Use Custom Referral URL</strong><small>Set a specific referral value for the destination.</small></span></label></div><div class="referral-custom"><div class="form-grid">${input('Custom Referral URL', 'https://referrer.example.com', false, 'url', 'id="custom-referral-url"')} ${input('Referral parameter name', 'e.g. referrer', false, 'text', 'id="referral-parameter"')}</div><p class="field-help">Use this URL as the referral/referrer value for the destination.</p></div><div class="referral-preview"><span>Configured behavior</span><strong id="referral-preview">The original referral value will be hidden from the destination.</strong></div>`, true)}
        ${section('Time Targeting', `<div class="time-enable">${toggle('Enable time targeting', false, 'time-toggle')}<p>Time targeting uses a 24-hour clock and the timezone selected below.</p></div><div class="time-fields">${select('Timezone', ['Asia/Kolkata (GMT+05:30)', 'UTC (GMT+00:00)', 'America/New_York (GMT-05:00)', 'Europe/London (GMT+00:00)'])}${input('Start hour', '00', false, 'number', 'min="0" max="23"')}${input('End hour', '23', false, 'number', 'min="0" max="23"')}<label class="check-field"><input type="checkbox"/> Enable inactive hours</label><div class="full day-picker"><span>Days</span>${['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'].map(x => `<label><input type="checkbox" checked/>${x}</label>`).join('')}</div>${input('Start date', '', false, 'date')}${input('End date', '', false, 'date')}</div>`, true, false)}
      </form></div>
      <footer class="action-bar"><p id="form-message" role="status"></p><div><button class="btn btn-quiet" type="button" id="cancel-campaign">Cancel</button><button class="btn btn-outline" type="button" id="save-draft">Save Draft</button><button class="btn btn-primary" type="submit" form="campaign-form">${icon('plus')} Create Campaign</button></div></footer>
    </main>
  </div>`;

  bindAppShell();

  if (editId) {
    document.querySelector('.page-intro h1')!.textContent = 'Edit Campaign';
    document.querySelector('.page-intro p:last-child')!.textContent = `Update campaign ID ${editId} and save your changes.`;
    document.querySelector('.crumb strong')!.textContent = 'Edit Campaign';
    document.querySelector<HTMLButtonElement>('[form="campaign-form"]')!.textContent = 'Save Changes';
    document.querySelector('#save-draft')?.remove();
    const fields = document.querySelectorAll<HTMLInputElement>('input');
    fields.forEach(field => { if (field.placeholder.includes('Summer acquisition')) field.value = `Campaign ${editId}`; if (field.placeholder.includes('click_id')) field.value = `https://destination.example.com/campaign/${editId}?click_id={click_id}`; });
  }
  document.querySelectorAll<HTMLInputElement>('input[placeholder="Optional app name"], input[placeholder="Optional app identifier"]').forEach(input => input.closest('label')?.classList.add('app-only'));
  const appFields = [...document.querySelectorAll<HTMLElement>('.app-only')];
  const syncObjective = () => { const app = [...document.querySelectorAll<HTMLInputElement>('input[name="objective"]')].find(input => input.checked)?.parentElement?.textContent?.includes('App Installs'); appFields.forEach(field => field.classList.toggle('objective-visible', Boolean(app))); appFields.forEach(field => field.querySelectorAll<HTMLInputElement>('input').forEach(input => input.required = Boolean(app))); };
  document.querySelectorAll<HTMLInputElement>('input[name="objective"]').forEach(input => input.addEventListener('change', syncObjective));
  syncObjective();
  const form = document.querySelector<HTMLFormElement>('#campaign-form')!;
  const message = document.querySelector<HTMLElement>('#form-message')!;
  const setExpanded = (selector: string, enabled: boolean) => document.querySelector(selector)?.classList.toggle('revealed', enabled);
  document.querySelectorAll<HTMLButtonElement>('.accordion-trigger').forEach(button => button.addEventListener('click', () => { const card = button.closest('.accordion')!; const open = card.classList.toggle('is-open'); button.setAttribute('aria-expanded', String(open)); }));
  document.querySelector<HTMLInputElement>('#date-toggle')?.addEventListener('change', e => setExpanded('.date-fields', (e.target as HTMLInputElement).checked));
  document.querySelector<HTMLInputElement>('#schedule-toggle')?.addEventListener('change', e => setExpanded('.schedule-fields', (e.target as HTMLInputElement).checked));
  document.querySelector<HTMLInputElement>('#time-toggle')?.addEventListener('change', e => setExpanded('.time-fields', (e.target as HTMLInputElement).checked));
  const referralOptions = [...document.querySelectorAll<HTMLInputElement>('input[name="referral-mode"]')];
  const referralCustom = document.querySelector<HTMLElement>('.referral-custom')!;
  const referralUrl = document.querySelector<HTMLInputElement>('#custom-referral-url')!;
  const referralParameter = document.querySelector<HTMLInputElement>('#referral-parameter')!;
  const referralPreview = document.querySelector<HTMLElement>('#referral-preview')!;
  const updateReferral = () => { const custom = referralOptions.some(option => option.checked && option.value === 'custom'); referralCustom.classList.toggle('revealed', custom); referralUrl.required = custom; document.querySelectorAll('.referral-option').forEach(option => option.classList.toggle('selected', (option.querySelector('input') as HTMLInputElement).checked)); const parameter = referralParameter.value.trim() || 'referrer'; referralPreview.textContent = custom ? (referralUrl.value.trim() ? `The destination will receive “${referralUrl.value.trim()}” as ${parameter}.` : `Enter a custom URL to use as ${parameter}.`) : 'The original referral value will be hidden from the destination.'; };
  referralOptions.forEach(option => option.addEventListener('change', updateReferral));
  referralUrl.addEventListener('input', updateReferral);
  referralParameter.addEventListener('input', updateReferral);
  document.querySelectorAll<HTMLButtonElement>('[data-token]').forEach(button => button.addEventListener('click', () => { const url = form.querySelector<HTMLInputElement>('input[placeholder*="click_id"]')!; url.value += button.dataset.token; url.focus(); }));
  document.querySelector('#save-draft')?.addEventListener('click', () => { message.textContent = 'Draft is held in this browser session and ready for API integration.'; document.querySelector('.draft-badge')!.textContent = 'Draft · Local'; });
  document.querySelector('#cancel-campaign')?.addEventListener('click', () => { form.reset(); message.textContent = 'Changes cleared from the form.'; });
  form.addEventListener('submit', event => { event.preventDefault(); message.textContent = ''; const numberInputs = [...form.querySelectorAll<HTMLInputElement>('input[type="number"]')]; numberInputs.forEach(field => field.setCustomValidity('')); const startHour = numberInputs.find(field => field.placeholder === '00'); const endHour = [...numberInputs].reverse().find(field => field.placeholder === '23'); if (startHour?.value && endHour?.value && Number(startHour.value) >= Number(endHour.value)) endHour.setCustomValidity('End hour must be after start hour.'); const dates = [...form.querySelectorAll<HTMLInputElement>('input[type="datetime-local"], input[type="date"]')].filter(field => field.value); for (let i = 0; i < dates.length - 1; i += 2) if (dates[i].value > dates[i + 1].value) dates[i + 1].setCustomValidity('End date must be after start date.'); if (!form.checkValidity()) { form.classList.add('was-validated'); message.textContent = 'Complete the highlighted required fields and correct date or time ranges before creating this campaign.'; form.querySelector<HTMLElement>(':invalid')?.focus(); return; } const campaignUrl = form.querySelector<HTMLInputElement>('input[placeholder*="click_id"]')!; try { new URL(campaignUrl.value); message.textContent = 'Campaign is ready to create when an API connection is available.'; } catch { campaignUrl.setCustomValidity('Enter a valid campaign URL.'); form.classList.add('was-validated'); campaignUrl.focus(); message.textContent = 'Enter a valid default campaign URL.'; } });
}
